from sqlalchemy import Column, Integer, BigInteger, String, Numeric, DateTime, Boolean, Text, PrimaryKeyConstraint
from app.core.database import Base


class SaleOrderDetail(Base):
    """
    Modelo para tbSaleOrderDetail del ERP
    Detalle de órdenes de venta (líneas/items de cada orden)
    """
    __tablename__ = "tb_sale_order_detail"
    __table_args__ = (
        PrimaryKeyConstraint('comp_id', 'bra_id', 'soh_id', 'sod_id'),
    )

    # Composite Primary Key
    comp_id = Column(Integer, nullable=False, index=True)
    bra_id = Column(Integer, nullable=False, index=True)
    soh_id = Column(BigInteger, nullable=False, index=True)
    sod_id = Column(BigInteger, nullable=False, index=True)

    # Campos principales (todos en minúsculas para PostgreSQL)
    sod_priority = Column(Integer)
    item_id = Column(Integer, index=True)
    sod_detail = Column(Text)
    curr_id = Column(Integer)
    sod_initqty = Column(Numeric(18, 6))
    sod_qty = Column(Numeric(18, 6))
    prli_id = Column(Integer, index=True)
    sod_price = Column(Numeric(18, 6))
    stor_id = Column(Integer)
    sod_lastupdate = Column(DateTime)
    sod_isediting = Column(Boolean)
    sod_insertdate = Column(DateTime)
    user_id = Column(Integer)
    sod_quotation = Column(String(100))
    sod_iscredit = Column(Boolean)
    sod_cost = Column(Numeric(18, 6))
    sod_costtax = Column(Numeric(18, 6))
    rmah_id = Column(Integer)
    rmad_id = Column(Integer)
    sod_note1 = Column(Text)
    sod_note2 = Column(Text)
    sod_itemdiscount = Column(Numeric(18, 6))
    sod_tis_id_origin = Column(BigInteger)
    sod_item_id_origin = Column(Integer)
    sod_isparentassociate = Column(Boolean)
    is_id = Column(Integer)
    it_transaction = Column(BigInteger)
    sod_ismade = Column(Boolean)
    sod_expirationdate = Column(DateTime)
    acc_count_id = Column(Integer)
    sod_packagesqty = Column(Integer)
    item_id_ew = Column(Integer)
    tis_idofthisew = Column(BigInteger)
    camp_id = Column(Integer)
    sdlmt_id = Column(Integer)
    sreas_id = Column(Integer)
    sod_loannumberofpays = Column(Integer)
    sod_loandateoffirstpay = Column(DateTime)
    sod_loandayofmonthofnextpays = Column(Integer)
    sod_itemdeliverydate = Column(DateTime)
    sod_idofthisew = Column(BigInteger)
    sod_isfrompconfigctrlid = Column(Integer)
    sod_ewaddress = Column(Text)
    sod_pcconfgistransfered2branch = Column(Boolean)
    sod_mlcost = Column(Numeric(18, 6))
    sod_itemassociationcoeficient = Column(Numeric(18, 6))
    ws_price = Column(Numeric(18, 6))
    ws_curr_id = Column(Integer)
    sops_id = Column(BigInteger)
    mlo_id = Column(BigInteger, index=True)
    sops_supp_id = Column(Integer)
    sops_bra_id = Column(Integer)
    sops_date = Column(DateTime)
    sod_mecost = Column(Numeric(18, 6))
    sod_mpcost = Column(Numeric(18, 6))
    sod_isdivided = Column(Boolean)
    sod_isdivided_date = Column(DateTime)
    user_id_division = Column(Integer)
    sodi_id = Column(BigInteger)
    sod_isdivided_costcoeficient = Column(Numeric(18, 6))
    sod_deliverycharge = Column(Numeric(18, 6))
    sod_itemdesc = Column(Text)
    sops_poh_bra_id = Column(Integer)
    sops_poh_id = Column(BigInteger)
    sops_note = Column(Text)
    sops_user_id = Column(Integer)
    sops_lastupdate = Column(DateTime)
    ct_transaction_selectfrompacking = Column(BigInteger)
    sodt_qty = Column(Numeric(18, 6))
    sod_disableprintinemmition = Column(Boolean)
    sod_discountbyitem = Column(Numeric(18, 6))
    sod_discountbytotal = Column(Numeric(18, 6))
    sod_creditint = Column(Numeric(18, 6))
    sod_creditintplus = Column(Numeric(18, 6))
    sod_priceneto = Column(Numeric(18, 6))
    sod_combocoeficient = Column(Numeric(18, 6))
    sod_montlypaymentfrom = Column(Numeric(18, 6))
    sod_montlypaymentto = Column(Numeric(18, 6))
    wscup_id = Column(Integer)
    sod_candeletecomboinso = Column(Boolean)
    sod_exclude4availablestock = Column(Boolean)
    sod_discountplan = Column(Numeric(18, 6))
    tax_id4iva = Column(Integer)
    sod_pending4pod_idrelation = Column(BigInteger)
    sod_mercadolibre_mustupdatestock = Column(Boolean)
    sod_auxtmpvalue = Column(Numeric(18, 6))
    sod_itemdiscount2 = Column(Numeric(18, 6))

    def __repr__(self):
        return f"<SaleOrderDetail(soh_id={self.soh_id}, sod_id={self.sod_id}, item_id={self.item_id})>"
