from sqlalchemy import Column, Integer, BigInteger, String, Numeric, DateTime, Boolean, Text
from app.core.database import Base


class SaleOrderHeader(Base):
    """
    Modelo para tbSaleOrderHeader del ERP
    Cabecera de órdenes de venta
    """
    __tablename__ = "tb_sale_order_header"

    # Primary Key
    soh_id = Column(BigInteger, primary_key=True, index=True)

    # Campos principales
    comp_id = Column(Integer, index=True)
    bra_id = Column(Integer)
    soh_cd = Column(DateTime, index=True)
    soh_deliveryDate = Column(DateTime)
    soh_observation1 = Column(Text)
    soh_observation2 = Column(Text)
    soh_observation3 = Column(Text)
    soh_observation4 = Column(Text)
    soh_quotation = Column(String(100))
    sm_id = Column(Integer)
    cust_id = Column(Integer, index=True)
    st_id = Column(Integer)
    disc_id = Column(Integer)
    dl_id = Column(Integer)
    cb_id = Column(Integer)
    soh_lastUpdate = Column(DateTime)
    soh_limitDate = Column(DateTime)
    tt_id = Column(Integer)
    tt_class = Column(Integer)
    soh_StatusOf = Column(Integer)
    user_id = Column(Integer)
    soh_isEditing = Column(Boolean)
    soh_isEditingCd = Column(DateTime)
    df_id = Column(Integer)
    soh_total = Column(Numeric(18, 6))
    ssos_id = Column(Integer)
    soh_ExchangeToCustomerCurrency = Column(Numeric(18, 6))
    chp_id = Column(Integer)
    soh_PL_df_Id = Column(Integer)
    soh_CustomerCurrency = Column(Integer)
    soh_WithCollection = Column(Boolean)
    soh_WithCollectionGUID = Column(String(100))
    soh_discount = Column(Numeric(18, 6))
    soh_loan = Column(Numeric(18, 6))
    soh_packagesQty = Column(Integer)
    soh_internalAnnotation = Column(Text)
    curr_id4Exchange = Column(Integer)
    curr_idExchange = Column(Integer)
    soh_ATotal = Column(Numeric(18, 6))
    df_id4PL = Column(Integer)
    somp_id = Column(Integer)
    soh_FEIdNumber = Column(String(100))
    soh_inCash = Column(Boolean)
    custf_id = Column(Integer)
    cust_id_guarantor = Column(Integer)
    ccp_id = Column(Integer)
    soh_MLdeliveryLabel = Column(String(255))
    soh_deliveryAddress = Column(Text)
    soh_MLQuestionsAndAnswers = Column(Text)
    aux_3RDSales_lastCTTransaction = Column(BigInteger)
    soh_MLId = Column(String(100))
    soh_MLGUIA = Column(String(100))
    pro_id = Column(Integer)
    aux_collectionInterest_lastCTTransaction = Column(BigInteger)
    ws_cust_Id = Column(Integer)
    ws_internalID = Column(String(100))
    ws_paymentGateWayStatusID = Column(String(100))
    ws_paymentGateWayReferenceID = Column(String(100))
    ws_IPFrom = Column(String(100))
    ws_st_id = Column(Integer)
    ws_dl_id = Column(Integer)
    soh_htmlNote = Column(Text)
    prli_id = Column(Integer, index=True)
    stor_id = Column(Integer)
    mlo_id = Column(BigInteger, index=True)
    MLShippingID = Column(BigInteger)
    soh_exchange2Currency4Total = Column(Numeric(18, 6))
    soh_Currency4Total = Column(Integer)
    soh_uniqueID = Column(String(100))
    soh_note4ExternalUse = Column(Text)
    soh_autoprocessLastOrder = Column(Boolean)
    dc_id = Column(Integer)
    soh_isPrintedFromSOPreparation = Column(Boolean)
    soh_persistExchange = Column(Numeric(18, 6))
    ct_transaction_preCollection = Column(BigInteger)
    soh_iseMailEnvied = Column(Boolean)
    soh_deliveryLabel = Column(String(255))
    ct_transaction_preInvoice = Column(BigInteger)

    def __repr__(self):
        return f"<SaleOrderHeader(soh_id={self.soh_id}, comp_id={self.comp_id}, mlo_id={self.mlo_id})>"
