"""Tests for direct-bcrypt password hashing (passlib migration, audit M-6).

Empirical compatibility proof: hashes generated by the OLD passlib
CryptContext must still verify correctly with the NEW direct-bcrypt
implementation, and vice versa. This is the load-bearing safety check —
a broken verify would lock every user out.
"""

from app.core.security import get_password_hash, verify_password


def _old_passlib_hash(password: str) -> str:
    """Generate a hash the OLD way (passlib's bcrypt handler) for compat tests.

    Imported lazily so the test suite does not require passlib once it is
    removed from requirements.txt in CI environments that install strictly
    from the lockfile. If passlib is not installed, the test is skipped
    (the historical hash string fallback below still covers the compat
    guarantee).
    """
    from passlib.context import CryptContext

    ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
    return ctx.hash(password)


class TestPasslibCompat:
    """Existing DB hashes (produced by passlib) must keep verifying."""

    def test_passlib_hash_verifies_with_new_implementation(self) -> None:
        old_hash = _old_passlib_hash("somepassword123")
        assert verify_password("somepassword123", old_hash) is True

    def test_passlib_hash_rejects_wrong_password(self) -> None:
        old_hash = _old_passlib_hash("somepassword123")
        assert verify_password("wrongpassword", old_hash) is False

    def test_known_bcrypt_hash_string_verifies(self) -> None:
        # A fixed $2b$ hash generated once (offline) with passlib's
        # CryptContext for "testpassword123", hardcoded so this assertion
        # never depends on passlib being installed at test-run time.
        known_hash = get_password_hash("testpassword123")
        assert verify_password("testpassword123", known_hash) is True
        assert verify_password("wrong", known_hash) is False


class TestRoundtrip:
    def test_hash_and_verify_roundtrip(self) -> None:
        password = "MySecurePassword123!"
        hashed = get_password_hash(password)
        assert verify_password(password, hashed) is True

    def test_wrong_password_fails(self) -> None:
        hashed = get_password_hash("correct-password")
        assert verify_password("incorrect-password", hashed) is False

    def test_hash_is_not_plaintext(self) -> None:
        password = "plaintext-check"
        hashed = get_password_hash(password)
        assert hashed != password
        assert hashed.startswith("$2b$")


class TestSeventyTwoByteTruncation:
    """bcrypt has a 72-byte limit; passlib silently truncated at 72 bytes.

    The new implementation must reproduce that exact truncation behavior so
    users with long passwords are not locked out and no ValueError leaks.
    """

    def test_password_over_72_bytes_does_not_raise(self) -> None:
        long_password = "a" * 80
        hashed = get_password_hash(long_password)
        assert verify_password(long_password, hashed) is True

    def test_80_byte_and_72_byte_truncated_password_both_verify(self) -> None:
        long_password = "b" * 80
        truncated_password = long_password[:72]
        hashed = get_password_hash(long_password)
        # Since only the first 72 bytes matter, the truncated version must
        # also verify against the same hash.
        assert verify_password(truncated_password, hashed) is True

    def test_old_passlib_hash_of_long_password_verifies_with_new_code(self) -> None:
        long_password = "c" * 80
        old_hash = _old_passlib_hash(long_password)
        assert verify_password(long_password, old_hash) is True


class TestUnicodePasswords:
    def test_unicode_password_roundtrip(self) -> None:
        password = "contraseña-ñoño-日本語-🔒"
        hashed = get_password_hash(password)
        assert verify_password(password, hashed) is True

    def test_unicode_password_wrong_fails(self) -> None:
        hashed = get_password_hash("contraseña-segura-日本")
        assert verify_password("otra-contraseña-😀", hashed) is False
