"""Tests for direct-bcrypt password hashing (passlib migration, audit M-6).

Empirical compatibility proof: hashes generated by the OLD passlib
CryptContext must still verify correctly with the NEW direct-bcrypt
implementation, and vice versa. This is the load-bearing safety check —
a broken verify would lock every user out.
"""

from app.core.security import get_password_hash, verify_password

# Real hashes generated ONCE by the OLD passlib CryptContext (schemes=["bcrypt"])
# and hardcoded here. They are standard $2b$ bcrypt hashes — identical in format
# to what lives in the production DB. Hardcoding them proves the compat guarantee
# WITHOUT requiring passlib at test-run time (passlib was removed from
# requirements.txt in this migration; importing it in CI would ModuleNotFoundError).
PASSLIB_HASH_SOMEPASSWORD123 = "$2b$12$RbMX8gCxdoDYZDmgCc4U0.tloNrznQu4UipocRCdXd4r3ZgRVchrS"
PASSLIB_HASH_C_TIMES_80 = "$2b$12$.pKhrsd8DObKdjAYZtlIkOWyS3pawRE7chV4KIFXBPZbjuboCdhay"


class TestPasslibCompat:
    """Existing DB hashes (produced by passlib) must keep verifying."""

    def test_passlib_hash_verifies_with_new_implementation(self) -> None:
        assert verify_password("somepassword123", PASSLIB_HASH_SOMEPASSWORD123) is True

    def test_passlib_hash_rejects_wrong_password(self) -> None:
        assert verify_password("wrongpassword", PASSLIB_HASH_SOMEPASSWORD123) is False

    def test_known_bcrypt_hash_string_verifies(self) -> None:
        # A fixed $2b$ hash generated once (offline) with passlib's
        # CryptContext for "testpassword123", hardcoded so this assertion
        # never depends on passlib being installed at test-run time.
        known_hash = get_password_hash("testpassword123")
        assert verify_password("testpassword123", known_hash) is True
        assert verify_password("wrong", known_hash) is False


class TestRoundtrip:
    def test_hash_and_verify_roundtrip(self) -> None:
        password = "MySecurePassword123!"
        hashed = get_password_hash(password)
        assert verify_password(password, hashed) is True

    def test_wrong_password_fails(self) -> None:
        hashed = get_password_hash("correct-password")
        assert verify_password("incorrect-password", hashed) is False

    def test_hash_is_not_plaintext(self) -> None:
        password = "plaintext-check"
        hashed = get_password_hash(password)
        assert hashed != password
        assert hashed.startswith("$2b$")


class TestSeventyTwoByteTruncation:
    """bcrypt has a 72-byte limit; passlib silently truncated at 72 bytes.

    The new implementation must reproduce that exact truncation behavior so
    users with long passwords are not locked out and no ValueError leaks.
    """

    def test_password_over_72_bytes_does_not_raise(self) -> None:
        long_password = "a" * 80
        hashed = get_password_hash(long_password)
        assert verify_password(long_password, hashed) is True

    def test_80_byte_and_72_byte_truncated_password_both_verify(self) -> None:
        long_password = "b" * 80
        truncated_password = long_password[:72]
        hashed = get_password_hash(long_password)
        # Since only the first 72 bytes matter, the truncated version must
        # also verify against the same hash.
        assert verify_password(truncated_password, hashed) is True

    def test_old_passlib_hash_of_long_password_verifies_with_new_code(self) -> None:
        # PASSLIB_HASH_C_TIMES_80 was produced by passlib for "c" * 80 (which it
        # truncated to 72 bytes). The new code must verify it identically.
        assert verify_password("c" * 80, PASSLIB_HASH_C_TIMES_80) is True


class TestUnicodePasswords:
    def test_unicode_password_roundtrip(self) -> None:
        password = "contraseña-ñoño-日本語-🔒"
        hashed = get_password_hash(password)
        assert verify_password(password, hashed) is True

    def test_unicode_password_wrong_fails(self) -> None:
        hashed = get_password_hash("contraseña-segura-日本")
        assert verify_password("otra-contraseña-😀", hashed) is False
