/**
 * Realistic fixtures for the Ventas ML screen's visual test.
 *
 * Every shape mirrors the backend's Pydantic models in
 * `backend/app/routers/ml_ventas_ops.py` field by field (`SaleListItem`,
 * `SaleGroup`, `SaleFacetCounts`, `SaleListResponse`, `SalesKpiResponse`,
 * `SaleCentricOperation`, `PackOperationSummary`). The values are the ugly
 * real-world ones on purpose: long Spanish ML titles, a 3-item pack, negative
 * markups, a provisional Total Gauss, a cancellation, a mediation, a coupon and
 * alerts -- the cases a screen designed against tidy placeholder data breaks on.
 */

const BASE_DATE = '2026-09-21T12:12:00Z';

const item = (overrides) => ({
  item_id: 'MLA2060835678',
  variation_id: null,
  seller_sku: 'EPS-L3250',
  title: 'Impresora Multifunción Epson EcoTank L3250 Color Negro',
  quantity: 1,
  unit_price: 597408.67,
  ...overrides,
});

const order = (overrides) => ({
  order_id: 2000018567320906,
  pack_id: null,
  status: 'paid',
  date_created: BASE_DATE,
  ml_last_updated: BASE_DATE,
  buyer_nickname: 'JUAN_PEREZ_92',
  total_amount: 597408.67,
  paid_amount: 555729.0,
  currency_id: 'ARS',
  payment_status: 'approved',
  shipping_status: 'shipped',
  shipping_id: 44012876543,
  operation_status: 'paid',
  goods_status: 'in_transit',
  neto: 502165.91,
  modo_logistico: 'cross_docking',
  total_gauss: 118420.55,
  total_gauss_provisional: false,
  total_gauss_provisional_falta: null,
  neto_depositado: 500373.68,
  retenciones_recuperables: 1792.23,
  item_category: 'Impresoras',
  city: 'Palermo',
  province: 'Capital Federal',
  shipping_substatus: 'out_for_delivery',
  coupon_amount: null,
  metrics_state: 'ok',
  alert_level: 'ok',
  markup: 21.6,
  items: [item({})],
  ...overrides,
});

// A lone order's group mirrors its only member -- `SaleGroup` copies the
// money/status fields from the member when there is just one.
const lone = (o) => ({
  group_key: `order:${o.order_id}`,
  pack_id: null,
  date_created: o.date_created,
  ml_last_updated: o.ml_last_updated,
  buyer_nickname: o.buyer_nickname,
  total_amount: o.total_amount,
  currency_id: o.currency_id,
  operation_status: o.operation_status,
  goods_status: o.goods_status,
  orders: [o],
  neto: o.neto,
  modo_logistico: o.modo_logistico,
  total_gauss: o.total_gauss,
  total_gauss_provisional: o.total_gauss_provisional,
  total_gauss_provisional_falta: o.total_gauss_provisional_falta,
  neto_depositado: o.neto_depositado,
  retenciones_recuperables: o.retenciones_recuperables,
});

const sum = (orders, key) =>
  orders.every((o) => o[key] !== null && o[key] !== undefined)
    ? Math.round(orders.reduce((acc, o) => acc + o[key], 0) * 100) / 100
    : null;

const pack = (packId, orders, overrides = {}) => ({
  group_key: `pack:${packId}`,
  pack_id: packId,
  date_created: orders[0].date_created,
  ml_last_updated: orders[0].ml_last_updated,
  buyer_nickname: orders[0].buyer_nickname,
  total_amount: sum(orders, 'total_amount'),
  currency_id: 'ARS',
  operation_status: orders[0].operation_status,
  goods_status: orders[0].goods_status,
  orders,
  neto: sum(orders, 'neto'),
  modo_logistico: orders[0].modo_logistico,
  total_gauss: sum(orders, 'total_gauss'),
  total_gauss_provisional: orders.some((o) => o.total_gauss_provisional),
  total_gauss_provisional_falta: orders.some((o) => o.total_gauss_provisional) ? 'Envío Flex' : null,
  neto_depositado: sum(orders, 'neto_depositado'),
  retenciones_recuperables: sum(orders, 'retenciones_recuperables'),
  ...overrides,
});

const EPSON = order({});

const PACK_ID = 2000014907031737;
const PACK_ORDERS = [
  order({
    order_id: 2000018567320911,
    pack_id: PACK_ID,
    buyer_nickname: 'pyme_soluciones_cordoba',
    total_amount: 1120000,
    paid_amount: 1120000,
    shipping_id: 44012876600,
    operation_status: 'paid',
    goods_status: 'in_warehouse',
    shipping_status: 'ready_to_ship',
    shipping_substatus: 'ready_to_print',
    neto: 930000,
    modo_logistico: 'self_service',
    total_gauss: 140000,
    total_gauss_provisional: true,
    total_gauss_provisional_falta: 'Envío Flex',
    neto_depositado: 930000,
    retenciones_recuperables: null,
    item_category: 'Notebooks',
    city: 'Nueva Córdoba',
    province: 'Córdoba',
    markup: 17.7,
    items: [
      item({
        item_id: 'MLA1429582101',
        seller_sku: 'LEN-82YU000PAR',
        title: 'Notebook Lenovo V15 G4 AMN Ryzen 5 7520U 8GB 256GB SSD 15.6" Full HD Windows 11',
        unit_price: 1120000,
      }),
    ],
  }),
  order({
    order_id: 2000018567320912,
    pack_id: PACK_ID,
    buyer_nickname: 'pyme_soluciones_cordoba',
    total_amount: 360000,
    paid_amount: 360000,
    shipping_id: 44012876600,
    goods_status: 'in_warehouse',
    shipping_status: 'ready_to_ship',
    shipping_substatus: 'ready_to_print',
    neto: 298400,
    modo_logistico: 'self_service',
    total_gauss: 77900,
    total_gauss_provisional: true,
    total_gauss_provisional_falta: 'Envío Flex',
    neto_depositado: 298400,
    retenciones_recuperables: null,
    item_category: 'Monitores',
    city: 'Nueva Córdoba',
    province: 'Córdoba',
    markup: 35.3,
    items: [
      item({
        item_id: 'MLA1198421099',
        seller_sku: 'SAM-LS24C310',
        title: 'Monitor Samsung Essential S3 24" FHD 75Hz IPS Borderless LS24C310EALXZB',
        unit_price: 360000,
      }),
    ],
  }),
  order({
    order_id: 2000018567320913,
    pack_id: PACK_ID,
    buyer_nickname: 'pyme_soluciones_cordoba',
    total_amount: 89990,
    paid_amount: 89990,
    shipping_id: 44012876600,
    goods_status: 'in_warehouse',
    shipping_status: 'ready_to_ship',
    shipping_substatus: 'ready_to_print',
    neto: 70120.4,
    modo_logistico: 'self_service',
    total_gauss: -4210.3,
    total_gauss_provisional: true,
    total_gauss_provisional_falta: 'Envío Flex',
    neto_depositado: 70120.4,
    retenciones_recuperables: null,
    item_category: 'Mouses',
    city: 'Nueva Córdoba',
    province: 'Córdoba',
    markup: -5.4,
    items: [
      item({
        item_id: 'MLA1388776655',
        seller_sku: 'LOG-910-006144',
        title: 'Mouse Inalámbrico Logitech MX Master 3S Grafito Bluetooth Silencioso',
        quantity: 2,
        unit_price: 44995,
      }),
    ],
  }),
];

const TV = order({
  order_id: 2000018567320042,
  buyer_nickname: 'marisa_gomez',
  total_amount: 489999,
  paid_amount: 489999,
  shipping_id: 44012871111,
  goods_status: 'delivered',
  shipping_status: 'delivered',
  shipping_substatus: null,
  neto: 401230.12,
  modo_logistico: 'fulfillment',
  total_gauss: -32450.8,
  neto_depositado: 401230.12,
  retenciones_recuperables: null,
  item_category: 'Televisores',
  city: 'Rosario',
  province: 'Santa Fe',
  markup: -8.4,
  items: [
    item({
      item_id: 'MLA1384910283',
      seller_sku: 'SAM-UN50CU7000',
      title: 'Smart TV Samsung 50" Crystal UHD 4K UN50CU7000GCZB Tizen Negro',
      unit_price: 489999,
    }),
  ],
});

const CAFETERA = order({
  order_id: 2000018567319830,
  buyer_nickname: 'lucas_cordoba',
  status: 'cancelled',
  total_amount: 215000,
  paid_amount: 0,
  shipping_id: 44012870222,
  operation_status: 'cancelled',
  goods_status: 'returned_undelivered',
  shipping_status: 'not_delivered',
  shipping_substatus: 'returned_to_warehouse',
  neto: 0,
  modo_logistico: 'cross_docking',
  total_gauss: null,
  neto_depositado: 0,
  retenciones_recuperables: null,
  item_category: 'Cafeteras',
  city: 'Godoy Cruz',
  province: 'Mendoza',
  markup: null,
  items: [
    item({
      item_id: 'MLA9023418290',
      seller_sku: 'OST-BVSTEM6603R',
      title: 'Cafetera Espresso Oster Prima Latte II BVSTEM6603R 15 Bares Roja',
      unit_price: 215000,
    }),
  ],
});

const AIRE = order({
  order_id: 2000018567319502,
  buyer_nickname: 'distribuidora_norte_tucuman',
  total_amount: 1249999,
  paid_amount: 1249999,
  shipping_id: 44012870333,
  operation_status: 'in_dispute',
  goods_status: 'delivered',
  shipping_status: 'delivered',
  shipping_substatus: null,
  neto: 1032500.5,
  modo_logistico: 'cross_docking',
  total_gauss: 64210.0,
  neto_depositado: 1032500.5,
  retenciones_recuperables: null,
  item_category: 'Aires Acondicionados',
  city: 'San Miguel de Tucumán',
  province: 'Tucumán',
  alert_level: 'warning',
  // Below the 6% "good" line: the amber case.
  markup: 4.2,
  items: [
    item({
      item_id: 'MLA1029384756',
      seller_sku: 'BGH-BS35WCCR',
      title: 'Aire Acondicionado Split BGH Silent Air 3500W Frío/Calor BS35WCCR Inverter Blanco',
      unit_price: 1249999,
    }),
  ],
});

const SONY = order({
  order_id: 2000018567319210,
  buyer_nickname: 'diego_audio',
  total_amount: 459999,
  paid_amount: 418319.33,
  shipping_id: 44012870444,
  goods_status: 'delivered',
  shipping_status: 'delivered',
  shipping_substatus: null,
  neto: 382450.0,
  modo_logistico: 'self_service',
  total_gauss: 70120.0,
  neto_depositado: 382450.0,
  retenciones_recuperables: null,
  item_category: 'Auriculares',
  city: 'CABA',
  province: 'Capital Federal',
  coupon_amount: 41679.67,
  markup: 22.5,
  items: [
    item({
      item_id: 'MLA1309284192',
      seller_sku: 'SONY-WH1000XM5',
      title: 'Auriculares Inalámbricos Sony WH-1000XM5 Negro Noise Cancelling Bluetooth',
      unit_price: 459999,
    }),
  ],
});

const ALERTA = order({
  order_id: 2000018567318801,
  buyer_nickname: 'compras_estudio_contable_ramirez',
  total_amount: 74999,
  paid_amount: 74999,
  shipping_id: 44012870555,
  operation_status: 'unknown',
  goods_status: 'unknown',
  shipping_status: 'handling',
  shipping_substatus: null,
  neto: null,
  modo_logistico: 'cross_docking',
  total_gauss: null,
  neto_depositado: null,
  retenciones_recuperables: null,
  item_category: 'Cables',
  city: 'La Plata',
  province: 'Buenos Aires',
  metrics_state: 'failed',
  alert_level: 'error',
  markup: null,
  items: [
    item({
      item_id: 'MLA1555000111',
      seller_sku: 'TPL-UE300',
      title: 'Adaptador De Red Usb 3.0 A Ethernet Gigabit Tp-link Ue300',
      unit_price: 74999,
    }),
  ],
});

const RECALC = order({
  order_id: 2000018567318402,
  buyer_nickname: 'ferreteria_el_tornillo',
  total_amount: 132500,
  paid_amount: 132500,
  shipping_id: 44012870666,
  operation_status: 'delivered',
  goods_status: 'delivered',
  shipping_status: 'delivered',
  shipping_substatus: null,
  neto: 110300,
  modo_logistico: 'retiro',
  total_gauss: 9000,
  metrics_state: 'recalculating',
  item_category: 'Herramientas',
  city: null,
  province: null,
  markup: 4.1,
  items: [
    item({
      item_id: 'MLA1777000222',
      seller_sku: 'BOS-GSB550',
      title: 'Taladro Percutor Bosch GSB 550 RE 550W Con Maletín Y 5 Mechas',
      unit_price: 132500,
    }),
  ],
});

export const SALES_RESPONSE = {
  total: 1284,
  limit: 25,
  offset: 0,
  sales: [
    lone(EPSON),
    pack(PACK_ID, PACK_ORDERS),
    lone(TV),
    lone(CAFETERA),
    lone(AIRE),
    lone(SONY),
    lone(ALERTA),
    lone(RECALC),
  ],
  facets: {
    operation_status: {
      paid: 1142,
      cancelled: 68,
      cancelled_ml_covered: 4,
      in_dispute: 32,
      delivered: 21,
      unknown: 17,
    },
    goods_status: {
      unknown: 17,
      in_warehouse: 89,
      in_transit: 412,
      delivered: 739,
      returned_undelivered: 44,
    },
    operation_status_total: 1284,
    goods_status_total: 1284,
    alerts_total: 19,
  },
};

export const PACK_GROUP_KEY = `pack:${PACK_ID}`;
export const EPSON_ORDER_ID = EPSON.order_id;

export const KPI_RESPONSE = {
  groups_count: 1284,
  orders_count: 1391,
  gross_billed_ars: 84920450.0,
  gross_billed_other: {},
  neto_sum: 68345120.5,
  neto_unknown_count: 3,
  total_gauss_sum: 14120900.1,
  total_gauss_ok_count: 1240,
  total_gauss_provisional_count: 12,
  total_gauss_unresolved_count: 11,
  markup_weighted_pct: 26.3,
  recalculating_count: 2,
  pending_count: 4,
  failed_count: 2,
  markup_skipped_count: 19,
  excluded_non_money_orders_count: 0,
  excluded_non_money_ars: 0,
  worker_alive: true,
  excluded_by_toggle: { a_revisar: 0, en_disputa: 0, mixta: 0, provisorio: 0, canceladas: 0 },
  effective_switches: {
    include_unknown: true,
    include_in_dispute: true,
    include_mixed: true,
    include_provisional: true,
    include_cancelled: true,
  },
};

export const ORDER_DETAIL_RESPONSE = {
  order: {
    order_id: EPSON.order_id,
    pack_id: null,
    status: 'paid',
    status_detail: null,
    buyer_id: 182736455,
    buyer_nickname: 'JUAN_PEREZ_92',
    seller_id: 999,
    total_amount: 597408.67,
    paid_amount: 555729.0,
    currency_id: 'ARS',
    buyer_first_name: 'Juan Carlos',
    buyer_last_name: 'Pérez',
    payment_method_id: 'master',
    installments: 6,
    payment_date_approved: '2026-09-21T12:13:00Z',
    coupon_amount: 41679.67,
  },
  items: [EPSON.items[0]],
  shipment: {
    shipment_id: 44012876543,
    status: 'shipped',
    substatus: 'out_for_delivery',
    tracking_number: 'MLA-COL-849201948',
    modo_logistico: 'cross_docking',
    city: 'Palermo',
    province: 'Capital Federal',
    estimated_delivery: '2026-09-23T00:00:00Z',
  },
  claim: null,
  questions: [],
  messages: [],
  breakdown: {
    lines: [
      { concepto: 'Cargo por vender', monto: 74676.08, origen: 'api' },
      { concepto: 'Envíos (Colecta)', monto: 15190.0, origen: 'api' },
      { concepto: 'Impuesto a los débitos y créditos', monto: 3584.45, origen: 'api' },
      { concepto: 'Retención IIBB (CABA) · SIRTAC', monto: 1792.23, origen: 'recuperable' },
    ],
    neto: 502165.91,
    incompleto: false,
    incomplete_reasons: [],
    monto_operacion: 597408.67,
    item_lines: [
      {
        item_id: 'MLA2060835678',
        variation_id: null,
        seller_sku: 'EPS-L3250',
        title: 'Impresora Multifunción Epson EcoTank L3250 Color Negro',
        quantity: 1,
        monto: 597408.67,
      },
    ],
    item_lines_reconcilia: true,
    item_lines_razon: null,
    neto_depositado: 500373.68,
    retenciones_recuperables: 1792.23,
  },
  total_gauss: 118420.55,
  iva_decomposicion: {
    componentes: [
      { concepto: 'Venta', alicuota: 21, bruto: 502165.91, base: 415013.15, iva: 87152.76, informativo: false },
      { concepto: 'SIRTAC', alicuota: null, bruto: 1792.23, base: 0, iva: 0, informativo: true },
    ],
    neto_sin_iva: 415013.15,
    reconcilia: true,
    diferencia: 0,
    razones: [],
    debitos_creditos_retiro: 0,
    base_venta_sin_iva: 415013.15,
  },
  cadena_total_gauss: {
    total_gauss: 118420.55,
    lineas: [
      { code: 'costo_mercaderia', monto: 284310.0, concepto: null, prorateado: false },
      { code: 'envio_flex', monto: null, concepto: 'Envío Flex', prorateado: false },
      { code: 'varios', monto: 12282.6, concepto: null, prorateado: false },
    ],
    markup: 21.6,
    provisional: true,
    provisional_falta: 'Envío Flex',
    costo_mercaderia_items: [
      {
        item_id: 'MLA2060835678',
        variation_id: null,
        title: 'Impresora Multifunción Epson EcoTank L3250 Color Negro',
        quantity: 1,
        conocido: true,
        moneda: 'USD',
        costo_origen: 198.5,
        tipo_cambio: 1432.29,
        tipo_cambio_fecha: '2026-09-20',
        costo_unitario_ars: 284310.0,
        fuente: 'erp_sku',
        costo_fecha: '2026-09-19',
      },
    ],
  },
  metrics_state: 'ok',
};

export const PACK_DETAIL_RESPONSE = {
  pack_id: PACK_ID,
  monto_operacion: 1569990,
  item_lines: PACK_ORDERS.map((o) => ({
    item_id: o.items[0].item_id,
    variation_id: null,
    seller_sku: o.items[0].seller_sku,
    title: o.items[0].title,
    quantity: o.items[0].quantity,
    monto: o.total_amount,
  })),
  item_lines_reconcilia: true,
  item_lines_razon: null,
  total_gauss: 213689.7,
  costo_mercaderia: 1105300,
  markup: 19.3,
  member_order_ids: PACK_ORDERS.map((o) => o.order_id),
};
