"""Initial tables

Revision ID: 7774f79045f7
Revises: 
Create Date: 2025-09-30 17:49:29.598890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7774f79045f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_erp',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('moneda_costo', sa.String(length=10), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('mla', sa.String(length=50), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('precio_publicado', sa.Float(), nullable=True),
    sa.Column('envio', sa.Float(), nullable=True),
    sa.Column('item_liquidation', sa.String(length=50), nullable=True),
    sa.Column('ultima_sync', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('hash_datos', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_productos_erp_codigo'), 'productos_erp', ['codigo'], unique=False)
    op.create_index(op.f('ix_productos_erp_item_id'), 'productos_erp', ['item_id'], unique=False)
    op.create_index(op.f('ix_productos_erp_mla'), 'productos_erp', ['mla'], unique=False)
    op.create_index(op.f('ix_productos_erp_subcategoria_id'), 'productos_erp', ['subcategoria_id'], unique=False)
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcat_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('comision_porcentaje', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategorias_id'), 'subcategorias', ['id'], unique=False)
    op.create_index(op.f('ix_subcategorias_subcat_id'), 'subcategorias', ['subcat_id'], unique=True)
    op.create_table('tipo_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('compra', sa.Float(), nullable=True),
    sa.Column('venta', sa.Float(), nullable=True),
    sa.Column('timestamp_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_cambio_fecha'), 'tipo_cambio', ['fecha'], unique=False)
    op.create_index(op.f('ix_tipo_cambio_id'), 'tipo_cambio', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_cambio_moneda'), 'tipo_cambio', ['moneda'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('ADMIN', 'PRICING_MANAGER', 'ANALISTA', 'AUDITOR', name='rolusuario'), nullable=True),
    sa.Column('auth_provider', sa.Enum('LOCAL', 'GOOGLE', name='authprovider'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('productos_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('precio_lista_ml', sa.Float(), nullable=True),
    sa.Column('moneda_lista', sa.String(length=10), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo_cambio', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['productos_erp.item_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_pricing_id'), 'productos_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_productos_pricing_item_id'), 'productos_pricing', ['item_id'], unique=True)
    op.create_table('historial_precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_pricing_id', sa.Integer(), nullable=True),
    sa.Column('precio_anterior', sa.Float(), nullable=True),
    sa.Column('precio_nuevo', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producto_pricing_id'], ['productos_pricing.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_precios_id'), 'historial_precios', ['id'], unique=False)
    op.create_index(op.f('ix_historial_precios_producto_pricing_id'), 'historial_precios', ['producto_pricing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_precios_producto_pricing_id'), table_name='historial_precios')
    op.drop_index(op.f('ix_historial_precios_id'), table_name='historial_precios')
    op.drop_table('historial_precios')
    op.drop_index(op.f('ix_productos_pricing_item_id'), table_name='productos_pricing')
    op.drop_index(op.f('ix_productos_pricing_id'), table_name='productos_pricing')
    op.drop_table('productos_pricing')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipo_cambio_moneda'), table_name='tipo_cambio')
    op.drop_index(op.f('ix_tipo_cambio_id'), table_name='tipo_cambio')
    op.drop_index(op.f('ix_tipo_cambio_fecha'), table_name='tipo_cambio')
    op.drop_table('tipo_cambio')
    op.drop_index(op.f('ix_subcategorias_subcat_id'), table_name='subcategorias')
    op.drop_index(op.f('ix_subcategorias_id'), table_name='subcategorias')
    op.drop_table('subcategorias')
    op.drop_index(op.f('ix_productos_erp_subcategoria_id'), table_name='productos_erp')
    op.drop_index(op.f('ix_productos_erp_mla'), table_name='productos_erp')
    op.drop_index(op.f('ix_productos_erp_item_id'), table_name='productos_erp')
    op.drop_index(op.f('ix_productos_erp_codigo'), table_name='productos_erp')
    op.drop_table('productos_erp')
    # ### end Alembic commands ###
