"""Add comision config tables

Revision ID: af88a834c830
Revises: 7774f79045f7
Create Date: 2025-10-01 11:29:52.003717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af88a834c830'
down_revision: Union[str, None] = '7774f79045f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones_por_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('pricelist4', sa.Integer(), nullable=True),
    sa.Column('comision_1_cuota', sa.Float(), nullable=True),
    sa.Column('comision_3_cuotas', sa.Float(), nullable=True),
    sa.Column('comision_6_cuotas', sa.Float(), nullable=True),
    sa.Column('comision_9_cuotas', sa.Float(), nullable=True),
    sa.Column('comision_12_cuotas', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comisiones_por_grupo_grupo_id'), 'comisiones_por_grupo', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_comisiones_por_grupo_id'), 'comisiones_por_grupo', ['id'], unique=False)
    op.create_index(op.f('ix_comisiones_por_grupo_pricelist4'), 'comisiones_por_grupo', ['pricelist4'], unique=False)
    op.create_table('grupos_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_comision_id'), 'grupos_comision', ['id'], unique=False)
    op.create_table('subcategorias_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcat_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('nombre_subcategoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategorias_grupos_grupo_id'), 'subcategorias_grupos', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_subcategorias_grupos_id'), 'subcategorias_grupos', ['id'], unique=False)
    op.create_index(op.f('ix_subcategorias_grupos_subcat_id'), 'subcategorias_grupos', ['subcat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategorias_grupos_subcat_id'), table_name='subcategorias_grupos')
    op.drop_index(op.f('ix_subcategorias_grupos_id'), table_name='subcategorias_grupos')
    op.drop_index(op.f('ix_subcategorias_grupos_grupo_id'), table_name='subcategorias_grupos')
    op.drop_table('subcategorias_grupos')
    op.drop_index(op.f('ix_grupos_comision_id'), table_name='grupos_comision')
    op.drop_table('grupos_comision')
    op.drop_index(op.f('ix_comisiones_por_grupo_pricelist4'), table_name='comisiones_por_grupo')
    op.drop_index(op.f('ix_comisiones_por_grupo_id'), table_name='comisiones_por_grupo')
    op.drop_index(op.f('ix_comisiones_por_grupo_grupo_id'), table_name='comisiones_por_grupo')
    op.drop_table('comisiones_por_grupo')
    # ### end Alembic commands ###
