"""Simplify comision config

Revision ID: d19958be66a1
Revises: ae02b9e92505
Create Date: 2025-10-01 11:40:50.079715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19958be66a1'
down_revision: Union[str, None] = 'ae02b9e92505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones_lista_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pricelist_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('comision_porcentaje', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comisiones_lista_grupo_grupo_id'), 'comisiones_lista_grupo', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_comisiones_lista_grupo_id'), 'comisiones_lista_grupo', ['id'], unique=False)
    op.create_index(op.f('ix_comisiones_lista_grupo_pricelist_id'), 'comisiones_lista_grupo', ['pricelist_id'], unique=False)
    op.drop_index('ix_comisiones_por_grupo_grupo_id', table_name='comisiones_por_grupo')
    op.drop_index('ix_comisiones_por_grupo_id', table_name='comisiones_por_grupo')
    op.drop_index('ix_comisiones_por_grupo_pricelist4', table_name='comisiones_por_grupo')
    op.drop_table('comisiones_por_grupo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones_por_grupo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pricelist4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comision_1_cuota', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comision_3_cuotas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comision_6_cuotas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comision_9_cuotas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comision_12_cuotas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='comisiones_por_grupo_pkey')
    )
    op.create_index('ix_comisiones_por_grupo_pricelist4', 'comisiones_por_grupo', ['pricelist4'], unique=False)
    op.create_index('ix_comisiones_por_grupo_id', 'comisiones_por_grupo', ['id'], unique=False)
    op.create_index('ix_comisiones_por_grupo_grupo_id', 'comisiones_por_grupo', ['grupo_id'], unique=False)
    op.drop_index(op.f('ix_comisiones_lista_grupo_pricelist_id'), table_name='comisiones_lista_grupo')
    op.drop_index(op.f('ix_comisiones_lista_grupo_id'), table_name='comisiones_lista_grupo')
    op.drop_index(op.f('ix_comisiones_lista_grupo_grupo_id'), table_name='comisiones_lista_grupo')
    op.drop_table('comisiones_lista_grupo')
    # ### end Alembic commands ###
