/**
 * Código de entidad BCRA (primeros 3 dígitos del CBU) → nombre del banco
 * Fuente: BCRA / Wikipedia "Clave Bancaria Uniforme"
 */
const CBU_BANCOS = {
  '005': 'The Royal Bank of Scotland',
  '007': 'Banco de Galicia y Buenos Aires',
  '011': 'Banco de la Nación Argentina',
  '014': 'Banco de la Provincia de Buenos Aires',
  '015': 'ICBC Argentina',
  '016': 'Citibank',
  '017': 'BBVA Banco Francés',
  '018': 'The Bank of Tokyo-Mitsubishi UFJ',
  '020': 'Banco de la Provincia de Córdoba',
  '027': 'Banco Supervielle',
  '029': 'Banco de la Ciudad de Buenos Aires',
  '030': 'Central de la República Argentina',
  '034': 'Banco Patagonia',
  '044': 'Banco Hipotecario',
  '045': 'Banco de San Juan',
  '046': 'Banco do Brasil',
  '060': 'Banco de Tucumán',
  '065': 'Banco Municipal de Rosario',
  '072': 'Banco Santander Río',
  '083': 'Banco del Chubut',
  '086': 'Banco de Santa Cruz',
  '093': 'Banco de la Pampa',
  '094': 'Banco de Corrientes',
  '097': 'Banco Provincia del Neuquén',
  '143': 'Brubank',
  '147': 'Banco Interfinanzas',
  '150': 'HSBC Bank Argentina',
  '158': 'Openbank',
  '165': 'JP Morgan Chase Bank',
  '191': 'Banco Credicoop',
  '198': 'Banco de Valores',
  '247': 'Banco Roela',
  '254': 'Banco Mariva',
  '259': 'Banco Itaú Argentina',
  '262': 'Bank of America',
  '266': 'BNP Paribas',
  '268': 'Banco Provincia de Tierra del Fuego',
  '269': 'Banco de la República Oriental del Uruguay',
  '277': 'Banco Sáenz',
  '281': 'Banco Meridian',
  '285': 'Banco Macro',
  '295': 'American Express Bank',
  '299': 'Banco Comafi',
  '300': 'Banco de Inversión y Comercio Exterior',
  '301': 'Banco Piano',
  '305': 'Banco Julio',
  '309': 'Nuevo Banco de la Rioja',
  '310': 'Banco del Sol',
  '311': 'Nuevo Banco del Chaco',
  '312': 'MBA Lazard Banco de Inversiones',
  '315': 'Banco de Formosa',
  '319': 'Banco CMF',
  '321': 'Banco de Santiago del Estero',
  '322': 'Banco Industrial',
  '325': 'Deutsche Bank',
  '330': 'Nuevo Banco de Santa Fe',
  '331': 'Banco Cetelem Argentina',
  '332': 'Banco de Servicios Financieros',
  '336': 'Banco Bradesco Argentina',
  '338': 'Banco de Servicios y Transacciones',
  '339': 'RCI Banque',
  '340': 'BACS Banco de Crédito y Securitización',
  '341': 'Más Ventas',
  '384': 'Wilobank',
  '386': 'Nuevo Banco de Entre Ríos',
  '389': 'Banco Columbia',
  '405': 'Ford Credit Compañía Financiera',
  '406': 'Metrópolis Compañía Financiera',
  '408': 'Compañía Financiera Argentina',
  '413': 'Montemar Compañía Financiera',
  '415': 'Transatlántica Compañía Financiera',
  '428': 'Caja de Crédito La Capital del Plata',
  '431': 'Banco Coinag',
  '432': 'Banco de Comercio',
  '434': 'Caja de Crédito Cuenca',
  '437': 'Volkswagen Credit Compañía Financiera',
  '438': 'Cordial Compañía Financiera',
  '440': 'Fiat Crédito Compañía Financiera',
  '441': 'GPAT Compañía Financiera',
  '442': 'Mercedes-Benz Compañía Financiera',
  '443': 'Rombo Compañía Financiera',
  '444': 'John Deere Credit Compañía Financiera',
  '445': 'PSA Finance Argentina',
  '446': 'Toyota Compañía Financiera',
  '448': 'Finandino Compañía Financiera',
  '453': 'Naranja X',
};

export default CBU_BANCOS;
